### Loading Datasets

In [12]:
import pandas as pd

enrol = pd.read_csv(
    "Aadhar Enrollment Dataset for Thane.csv",
    parse_dates=['date']
)

bio = pd.read_csv(
    "Aadhaar Biometric Monthly Update Data.csv",
    parse_dates=['date']
)

demo = pd.read_csv(
    "Aadhar Demographic Updates for Thane.csv",
    parse_dates=['date']
)

### Enrollment data validity check

In [14]:
enrol.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,01-09-2025,Maharashtra,Thane,401107,6,7,0
1,01-09-2025,Maharashtra,Thane,401203,1,0,0
2,01-09-2025,Maharashtra,Thane,401603,1,1,0
3,01-09-2025,Maharashtra,Thane,401606,1,0,0
4,01-09-2025,Maharashtra,Thane,421305,3,0,0

In [15]:
enrol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5064 entries, 0 to 5063
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            5064 non-null   object
 1   state           5064 non-null   object
 2   district        5064 non-null   object
 3   pincode         5064 non-null   int64
 4   age_0_5         5064 non-null   int64
 5   age_5_17        5064 non-null   int64
 6   age_18_greater  5064 non-null   int64
dtypes: int64(4), object(3)
memory usage: 277.1+ KB

### Demographic Data validity check

In [16]:
demo.head()

         date        state district  pincode  demo_age_5_17  demo_age_17_
0  01-03-2025  Maharashtra    Thane   400606            102          1021
1  01-03-2025  Maharashtra    Thane   400603             15           254
2  01-03-2025  Maharashtra    Thane   400708            131          1281
3  01-04-2025  Maharashtra    Thane   400612            611          3624
4  01-04-2025  Maharashtra    Thane   421301            301          2490

In [17]:
demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8849 entries, 0 to 8848
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           8849 non-null   object
 1   state          8849 non-null   object
 2   district       8849 non-null   object
 3   pincode        8849 non-null   int64
 4   demo_age_5_17  8849 non-null   int64
 5   demo_age_17_   8849 non-null   int64
dtypes: int64(3), object(3)
memory usage: 414.9+ KB

### Biometric Data Validity check

In [18]:
bio.head()

         date        state district  pincode  bio_age_5_17  bio_age_17_
0  01-03-2025  Maharashtra    Thane   401602            49          840
1  01-03-2025  Maharashtra    Thane   421503           403         1227
2  01-03-2025  Maharashtra    Thane   421001           116          455
3  01-03-2025  Maharashtra    Thane   421305           206          516
4  01-03-2025  Maharashtra    Thane   421601           316          441

In [19]:
bio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20196 entries, 0 to 20195
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          20196 non-null  object
 1   state         20196 non-null  object
 2   district      20196 non-null  object
 3   pincode       20196 non-null  int64
 4   bio_age_5_17  20196 non-null  int64
 5   bio_age_17_   20196 non-null  int64
dtypes: int64(3), object(3)
memory usage: 946.8+ KB

In [20]:
enrol = enrol[[
    'date', 'state', 'district', 'pincode',
    'age_0_5', 'age_5_17', 'age_18_greater'
]]

In [21]:
demo = demo[[
    'date', 'state', 'district', 'pincode',
    'demo_age_5_17', 'demo_age_17_'
]]

In [22]:
bio = bio[[
    'date', 'state', 'district', 'pincode',
    'bio_age_5_17', 'bio_age_17_'
]]

### Merging the columns

In [23]:
merged = pd.merge(
    enrol,
    demo,
    on=['date', 'state', 'district', 'pincode'],
    how='outer'
)

In [24]:
merged.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_
0,01-01-2026,Maharashtra,Thane,400601,14.0,3.0,0.0,3.0,31.0
1,01-01-2026,Maharashtra,Thane,400602,2.0,0.0,1.0,0.0,9.0
2,01-01-2026,Maharashtra,Thane,400603,1.0,0.0,0.0,0.0,2.0
3,01-01-2026,Maharashtra,Thane,400604,16.0,2.0,0.0,4.0,55.0
4,01-01-2026,Maharashtra,Thane,400605,13.0,6.0,0.0,7.0,44.0

In [25]:
merged.shape

(9989, 9)

In [26]:
merged = pd.merge(
    merged,
    bio,
    on=['date', 'state', 'district', 'pincode'],
    how='outer'
)

In [37]:
merged.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_
0,01-01-2026,Maharashtra,Thane,400601,14.0,3.0,0.0,3.0,31.0,48.0,67.0
1,01-01-2026,Maharashtra,Thane,400602,2.0,0.0,1.0,0.0,9.0,12.0,14.0
2,01-01-2026,Maharashtra,Thane,400602,2.0,0.0,1.0,0.0,9.0,12.0,14.0
3,01-01-2026,Maharashtra,Thane,400603,1.0,0.0,0.0,0.0,2.0,19.0,14.0
4,01-01-2026,Maharashtra,Thane,400604,16.0,2.0,0.0,4.0,55.0,0.0,0.0

In [28]:
merged.shape

(23042, 11)

In [30]:
merged.isnull().sum()

date                  0
state                 0
district              0
pincode               0
age_0_5           16560
age_5_17          16560
age_18_greater    16560
demo_age_5_17     11454
demo_age_17_      11454
bio_age_5_17       2846
bio_age_17_        2846
dtype: int64

### Handling NaN values

In [ ]:
numeric_cols = [
    'age_0_5', 'age_5_17', 'age_18_greater',
    'demo_age_5_17', 'demo_age_17_',
    'bio_age_5_17', 'bio_age_17_'
]

merged[numeric_cols] = merged[numeric_cols].fillna(0)

### Sanity check for merged columns

In [34]:
merged.isna().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
dtype: int64

In [35]:
merged[numeric_cols].dtypes

age_0_5           float64
age_5_17          float64
age_18_greater    float64
demo_age_5_17     float64
demo_age_17_      float64
bio_age_5_17      float64
bio_age_17_       float64
dtype: object

In [36]:
print("Enrol rows:", enrol.shape[0])
print("Demo rows:", demo.shape[0])
print("Bio rows:", bio.shape[0])
print("Merged rows:", merged.shape[0])

Enrol rows: 5064
Demo rows: 8849
Bio rows: 20196
Merged rows: 23042

### Save the merged file

In [41]:
merged = merged.sort_values(['pincode', 'date'])

merged.to_csv(
    'D:/UIDAI HACKATHON/UIDAI-Hackathon/data/processed/Aadhaar_daily.csv',
    index=False
)